import type { CorpusDocument, SourceProvenance } from './types.ts';
import { curatedContentHash } from './ingestion.ts';

type CuratedDocument = Omit<CorpusDocument, 'provenance'>;

const REVIEW_DATE = '2026-09-02';

function provenance(document: CuratedDocument): SourceProvenance {
  const rolling = document.sourceUrl.includes('/latest/') || document.sourceUrl.includes('docs.fluentbit.io');
  return {
    sourceVersion: rolling ? `rolling documentation reviewed ${REVIEW_DATE}` : `source snapshot reviewed ${REVIEW_DATE}`,
    retrievedAt: REVIEW_DATE,
    sourceSection: document.title,
    curatedContentHash: curatedContentHash(document),
    reviewStatus: 'curated-demo-review',
  };
}

const curatedDocuments: CuratedDocument[] = [
  {
    id: 'nvidia-xid-79',
    title: 'Xid 79: GPU has fallen off the bus',
    source: 'NVIDIA Xid Errors',
    sourceUrl: 'https://docs.nvidia.com/deploy/xid-errors/analyzing-xid-catalog.html',
    authority: 'official',
    signalTypes: ['xid'],
    identifiers: ['XID 79', 'XID_79'],
    gpuModels: ['A100', 'H100', 'H200', 'B100', 'GB200'],
    driverBranches: [],
    updated: '2026-05-01',
    content:
      'Xid 79 is reported when the NVIDIA driver can no longer access a GPU over its PCI Express connection. The event text commonly says GPU has fallen off the bus. Investigation should include earlier Xid events, host PCIe Advanced Error Reporting messages, power delivery, physical connectivity, and whether the device remains visible to the operating system.',
    documentedMeaning:
      'The NVIDIA driver reports that the GPU is no longer accessible over its PCIe connection.',
    nextEvidence: [
      'Inspect earlier NVRM/Xid events for the same PCI bus address.',
      'Collect host PCIe AER messages and confirm whether the device is still enumerated.',
      'Record GPU model, driver branch, firmware, node, and workload identity.',
    ],
    limitations: [
      'Xid 79 alone does not distinguish GPU hardware, power, slot, riser, or host PCIe-path failures.',
      'Do not infer that a process restart can recover a device the host can no longer enumerate.',
    ],
  },
  {
    id: 'nvidia-xid-48',
    title: 'Xid 48: double-bit ECC error',
    source: 'NVIDIA Xid Errors',
    sourceUrl: 'https://docs.nvidia.com/deploy/xid-errors/analyzing-xid-catalog.html',
    authority: 'official',
    signalTypes: ['xid'],
    identifiers: ['XID 48', 'XID_48'],
    gpuModels: ['A100', 'H100', 'H200', 'B100', 'GB200'],
    driverBranches: [],
    updated: '2026-05-01',
    content:
      'Xid 48 is associated with an uncorrectable double-bit ECC memory error. Correlate the event with volatile and aggregate ECC counters, row-remapping or page-retirement status where supported, the affected GPU UUID, and any later recovery-action event.',
    documentedMeaning:
      'The GPU reported an uncorrectable double-bit ECC memory error.',
    nextEvidence: [
      'Collect volatile and aggregate double-bit ECC counters for the affected GPU.',
      'Inspect row-remapping or page-retirement status when the GPU supports it.',
      'Check for a subsequent recovery-action event and preserve the GPU UUID.',
    ],
    limitations: [
      'A single counter snapshot does not show whether errors are new, historical, or still increasing.',
    ],
  },
  {
    id: 'nvidia-xid-31',
    title: 'Xid 31: GPU memory page fault',
    source: 'NVIDIA Xid Errors',
    sourceUrl: 'https://docs.nvidia.com/deploy/xid-errors/analyzing-xid-catalog.html',
    authority: 'official',
    signalTypes: ['xid'],
    identifiers: ['XID 31', 'XID_31'],
    gpuModels: [],
    driverBranches: [],
    updated: '2026-05-01',
    content:
      'Xid 31 reports a GPU memory-management-unit page fault. Application address use, driver behavior, and hardware conditions may all require investigation. Preserve the process, channel, workload, and surrounding driver messages rather than treating the identifier as a complete root cause.',
    documentedMeaning: 'The GPU memory-management unit reported a page fault.',
    nextEvidence: [
      'Capture the affected process, workload, channel, and nearby driver messages.',
      'Reproduce with application memory-checking or debugging tools when safe.',
    ],
    limitations: ['The event does not by itself identify the faulty source-code location or prove hardware failure.'],
  },
  {
    id: 'nvidia-xid-13',
    title: 'Xid 13: graphics engine exception',
    source: 'NVIDIA Xid Errors',
    sourceUrl: 'https://docs.nvidia.com/deploy/xid-errors/analyzing-xid-catalog.html',
    authority: 'official',
    signalTypes: ['xid'],
    identifiers: ['XID 13', 'XID_13'],
    gpuModels: [],
    driverBranches: [],
    updated: '2026-05-01',
    content:
      'Xid 13 indicates a graphics-engine exception. The surrounding exception data, application behavior, driver branch, and reproducibility are needed to separate an application fault from driver or hardware conditions.',
    documentedMeaning: 'The GPU reported a graphics-engine exception.',
    nextEvidence: [
      'Preserve the complete Xid line and surrounding exception data.',
      'Record whether the event follows one workload or occurs across unrelated workloads.',
    ],
    limitations: ['The identifier is a symptom class, not a unique root cause.'],
  },
  {
    id: 'nvidia-xid-43',
    title: 'Xid 43: GPU stopped processing',
    source: 'NVIDIA Xid Errors',
    sourceUrl: 'https://docs.nvidia.com/deploy/xid-errors/analyzing-xid-catalog.html',
    authority: 'official',
    signalTypes: ['xid'],
    identifiers: ['XID 43', 'XID_43'],
    gpuModels: [],
    driverBranches: [],
    updated: '2026-05-01',
    content:
      'Xid 43 indicates a software-induced fault: an application hit a fault and the GPU stopped its work. NVIDIA describes the GPU as remaining healthy for this event class. Preserve the affected process and preceding events because Xid 43 does not identify the source-code location by itself.',
    documentedMeaning: 'An application fault stopped GPU work; the event class does not by itself indicate an unhealthy GPU.',
    nextEvidence: ['Identify the affected application or container and inspect its preceding CUDA and driver errors.'],
    limitations: ['Xid 43 does not identify the faulty instruction or justify labeling the GPU hardware unhealthy.'],
  },
  {
    id: 'nvidia-xid-154',
    title: 'Xid 154: GPU recovery action',
    source: 'NVIDIA Xid Errors',
    sourceUrl: 'https://docs.nvidia.com/deploy/xid-errors/working-with-xid-errors.html',
    authority: 'official',
    signalTypes: ['xid'],
    identifiers: ['XID 154', 'XID_154'],
    gpuModels: ['A100', 'H100', 'H200', 'B100', 'GB200'],
    driverBranches: ['R565', 'R570', 'R575', 'R580'],
    updated: '2026-05-01',
    content:
      'Newer drivers can emit Xid 154 to report a GPU recovery action associated with another Xid. Read it together with the initiating event and preserve the action reported by the driver instead of inventing a generic restart recommendation.',
    documentedMeaning: 'The driver reported a recovery-action classification associated with a GPU event.',
    nextEvidence: ['Find the initiating Xid and record the exact recovery action reported by the driver.'],
    limitations: ['Applicability and action vocabulary depend on GPU and driver support.'],
  },
  {
    id: 'dcgm-pcie-replay',
    title: 'DCGM PCIe replay counter',
    source: 'NVIDIA DCGM Field Identifiers',
    sourceUrl: 'https://docs.nvidia.com/datacenter/dcgm/latest/reference/dcgm-fields.html',
    authority: 'official',
    signalTypes: ['metric'],
    identifiers: ['DCGM_FI_DEV_PCIE_REPLAY_COUNTER'],
    gpuModels: [],
    driverBranches: [],
    updated: '2026-07-01',
    content:
      'DCGM_FI_DEV_PCIE_REPLAY_COUNTER represents PCIe replay activity. Treat it as a cumulative counter and compare its rate or delta over a known interval. A raw value without a baseline does not establish an active fault.',
    documentedMeaning: 'The metric records PCIe replay activity for the GPU connection.',
    nextEvidence: [
      'Calculate the counter increase over a defined time window.',
      'Correlate increases with PCIe AER logs, Xid events, and workload timing.',
    ],
    limitations: ['A cumulative absolute value without a baseline cannot show when the replays occurred.'],
  },
  {
    id: 'dcgm-gpu-temp',
    title: 'DCGM GPU temperature',
    source: 'NVIDIA DCGM Exporter Metrics',
    sourceUrl: 'https://docs.nvidia.com/datacenter/dcgm/latest/reference/dcgm-exporter-metrics.html',
    authority: 'official',
    signalTypes: ['metric'],
    identifiers: ['DCGM_FI_DEV_GPU_TEMP', 'DCGM_FI_DEV_GPU_TEMP_CELSIUS'],
    gpuModels: [],
    driverBranches: [],
    updated: '2026-07-01',
    content:
      'DCGM_FI_DEV_GPU_TEMP is exported as a gauge and represents GPU temperature in Celsius. Interpret it with thermal-violation and clock-event signals, workload utilization, fan or cooling state, and a time series rather than one point.',
    documentedMeaning: 'The gauge reports GPU temperature in degrees Celsius.',
    nextEvidence: ['Collect a temperature time series with GPU utilization, power, and thermal-violation metrics.'],
    limitations: ['A single temperature sample does not prove thermal throttling.'],
  },
  {
    id: 'dcgm-power-usage',
    title: 'DCGM board power usage',
    source: 'NVIDIA DCGM Exporter Metrics',
    sourceUrl: 'https://docs.nvidia.com/datacenter/dcgm/latest/reference/dcgm-exporter-metrics.html',
    authority: 'official',
    signalTypes: ['metric'],
    identifiers: ['DCGM_FI_DEV_POWER_USAGE', 'DCGM_FI_DEV_BOARD_POWER_WATTS'],
    gpuModels: [],
    driverBranches: [],
    updated: '2026-07-01',
    content:
      'The exported DCGM_FI_DEV_POWER_USAGE gauge maps to board power in watts. Compare it with configured power limits, clock-event reasons, utilization, and workload phase.',
    documentedMeaning: 'The gauge reports GPU board power usage in watts.',
    nextEvidence: ['Compare power, utilization, clock events, and the configured power limit over the same interval.'],
    limitations: ['High power use can be expected under load and is not itself a failure.'],
  },
  {
    id: 'dcgm-ecc-dbe',
    title: 'DCGM double-bit ECC counters',
    source: 'NVIDIA DCGM Exporter Metrics',
    sourceUrl: 'https://docs.nvidia.com/datacenter/dcgm/latest/reference/dcgm-exporter-metrics.html',
    authority: 'official',
    signalTypes: ['metric'],
    identifiers: ['DCGM_FI_DEV_ECC_DBE_VOL_TOTAL', 'DCGM_FI_DEV_ECC_DBE_AGG_TOTAL'],
    gpuModels: [],
    driverBranches: [],
    updated: '2026-07-01',
    content:
      'DCGM double-bit ECC metrics separate volatile and aggregate totals. Volatile values relate to the current driver lifecycle while aggregate values preserve a broader history. Use deltas, GPU identity, and related Xid events.',
    documentedMeaning: 'The metrics count uncorrectable double-bit ECC events over volatile or aggregate lifetimes.',
    nextEvidence: ['Compare volatile and aggregate counters and determine whether the volatile counter is increasing.'],
    limitations: ['Metric availability and exact behavior depend on the GPU and DCGM support.'],
  },
  {
    id: 'dcgm-exporter-selection',
    title: 'DCGM Exporter metric selection and availability',
    source: 'NVIDIA DCGM Exporter Documentation',
    sourceUrl: 'https://docs.nvidia.com/datacenter/dcgm/latest/reference/dcgm-exporter-metrics.html',
    authority: 'official',
    signalTypes: ['metric', 'pipeline'],
    identifiers: ['DCGM_EXP_XID_ERRORS_COUNT', 'DCGM_EXP_GPU_HEALTH_STATUS'],
    gpuModels: [],
    driverBranches: [],
    updated: '2026-07-01',
    content:
      'DCGM Exporter exposes selected fields in Prometheus format. Selecting a field does not guarantee runtime emission because support also depends on DCGM, hardware, entity type, permissions, and deployment configuration. Exporter-owned Xid count and health metrics can be enabled when supported.',
    documentedMeaning: 'DCGM Exporter publishes configured and supported GPU telemetry as Prometheus metrics.',
    nextEvidence: ['Verify the active collector configuration and inspect the exporter metrics endpoint.'],
    limitations: ['Configured fields may remain absent when unsupported by the runtime GPU or DCGM combination.'],
  },
  {
    id: 'gpu-operator-telemetry',
    title: 'GPU Operator and DCGM Exporter telemetry',
    source: 'NVIDIA GPU Operator Documentation',
    sourceUrl: 'https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/getting-started.html',
    authority: 'official',
    signalTypes: ['pipeline', 'metric'],
    identifiers: ['GPU_OPERATOR', 'DCGM_EXPORTER'],
    gpuModels: [],
    driverBranches: [],
    updated: '2026-07-01',
    content:
      'The NVIDIA GPU Operator can deploy and manage DCGM and DCGM Exporter in Kubernetes. Exporter metrics can be associated with Kubernetes workloads through the pod-resources integration and scraped by Prometheus.',
    documentedMeaning: 'GPU Operator can supply the Kubernetes components used to expose DCGM telemetry.',
    nextEvidence: ['Verify exporter pods, ServiceMonitor discovery, and workload labels before debugging missing series.'],
    limitations: ['Installing the Operator does not guarantee that every optional field is enabled or supported.'],
  },
  {
    id: 'fluent-bit-kubernetes',
    title: 'Fluent Bit Kubernetes metadata enrichment',
    source: 'Fluent Bit Official Manual',
    sourceUrl: 'https://docs.fluentbit.io/manual/pipeline/filters/kubernetes',
    authority: 'official',
    signalTypes: ['pipeline'],
    identifiers: ['KUBERNETES_FILTER', 'FLUENT_BIT'],
    gpuModels: [],
    driverBranches: [],
    updated: '2026-03-01',
    content:
      'The Fluent Bit Kubernetes filter can enrich tailed container records with pod, namespace, container, owner, label, and annotation metadata. Correct tags, file paths, parser registration, and API or Kubelet access are prerequisites.',
    documentedMeaning: 'The Kubernetes filter attaches workload metadata to container log records.',
    nextEvidence: ['Verify the input tag, tag prefix, parser, service-account access, and metadata cache behavior.'],
    limitations: ['Host kernel logs need an explicit mapping strategy because they are not inherently pod-scoped.'],
  },
  {
    id: 'fluent-bit-otlp',
    title: 'Fluent Bit OpenTelemetry output',
    source: 'Fluent Bit Official Manual',
    sourceUrl: 'https://docs.fluentbit.io/manual/data-pipeline/outputs/opentelemetry',
    authority: 'official',
    signalTypes: ['pipeline'],
    identifiers: ['OTLP', 'FLUENT_BIT', '/V1/LOGS'],
    gpuModels: [],
    driverBranches: [],
    updated: '2026-05-01',
    content:
      'The Fluent Bit OpenTelemetry output can send logs, metrics, and traces to OpenTelemetry endpoints. Configure the destination, signal URI, transport, retry policy, TLS, and record-to-OTel field mappings deliberately.',
    documentedMeaning: 'Fluent Bit can forward supported telemetry signals to an OpenTelemetry endpoint.',
    nextEvidence: ['Confirm endpoint reachability, /v1/logs response status, retry behavior, TLS, and field mappings.'],
    limitations: ['Successful forwarding does not guarantee that downstream storage indexed every attribute.'],
  },
  {
    id: 'otel-semconv',
    title: 'OpenTelemetry semantic conventions',
    source: 'OpenTelemetry Specification',
    sourceUrl: 'https://opentelemetry.io/docs/specs/semconv/',
    authority: 'official',
    signalTypes: ['pipeline'],
    identifiers: ['OTEL', 'SEMANTIC_CONVENTIONS', 'TRACE_ID', 'SPAN_ID'],
    gpuModels: [],
    driverBranches: [],
    updated: '2026-08-01',
    content:
      'OpenTelemetry semantic conventions define common names and meanings for resource attributes, logs, metrics, spans, and events. Preserve original vendor identifiers such as Xid and DCGM field names while adding stable resource context such as service, host, and Kubernetes identity.',
    documentedMeaning: 'Semantic conventions provide consistent attribute naming across telemetry producers and consumers.',
    nextEvidence: ['Record the convention version and validate required resource identifiers at the collector boundary.'],
    limitations: ['Not every GPU-specific attribute has a stable cross-vendor semantic convention.'],
  },
  {
    id: 'nvidia-xid-74',
    title: 'Xid 74: NVLink error',
    source: 'NVIDIA Xid Errors',
    sourceUrl: 'https://docs.nvidia.com/deploy/xid-errors/analyzing-xid-catalog.html',
    authority: 'official',
    signalTypes: ['xid'],
    identifiers: ['XID 74', 'XID_74'],
    gpuModels: [],
    driverBranches: [],
    updated: '2026-05-01',
    content:
      'Xid 74 reports an NVLink error. Preserve the complete event, affected GPU UUID and topology, then correlate NVLink counters and Fabric Manager or NVSwitch events where the platform uses them. The identifier is not enough to name the failed link component.',
    documentedMeaning: 'The NVIDIA driver reported an NVLink error for the GPU.',
    nextEvidence: [
      'Capture GPU and NVLink topology plus the complete Xid line and nearby events.',
      'Inspect DCGM NVLink error counters and Fabric Manager or NVSwitch logs for the same interval.',
    ],
    limitations: ['Xid 74 alone does not identify whether the origin is a GPU link, switch path, software, or platform condition.'],
  },
  {
    id: 'dcgm-nvlink-errors',
    title: 'DCGM NVLink error and bandwidth counters',
    source: 'NVIDIA DCGM Field Identifiers',
    sourceUrl: 'https://docs.nvidia.com/datacenter/dcgm/latest/dcgm-api/dcgm-api-field-ids.html',
    authority: 'official',
    signalTypes: ['metric'],
    identifiers: ['DCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_TOTAL', 'DCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_TOTAL', 'DCGM_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_TOTAL'],
    gpuModels: [],
    driverBranches: [],
    updated: '2026-08-01',
    content:
      'DCGM exposes NVLink CRC and recovery error counters. Interpret cumulative values as deltas over a defined interval and bind them to GPU identity and topology. Correlate growth with Xid 74, Fabric Manager or NVSwitch events, and workload timing.',
    documentedMeaning: 'The fields count classes of NVLink transport errors observed for a GPU.',
    nextEvidence: ['Calculate per-link or per-GPU counter deltas and preserve the NVLink topology for the same window.'],
    limitations: ['A nonzero historical counter does not establish a current failure or identify the physical component.'],
  },
  {
    id: 'dcgm-row-remap',
    title: 'DCGM row-remapping and retired-page health',
    source: 'NVIDIA DCGM Field Identifiers',
    sourceUrl: 'https://docs.nvidia.com/datacenter/dcgm/latest/dcgm-api/dcgm-api-field-ids.html',
    authority: 'official',
    signalTypes: ['metric'],
    identifiers: ['DCGM_FI_DEV_ROW_REMAP_UNCORRECTABLE_TOTAL', 'DCGM_FI_DEV_ROW_REMAP_FAILED', 'DCGM_FI_DEV_ROW_REMAP_PENDING', 'DCGM_FI_DEV_PAGE_RETIRED_DBE_TOTAL', 'DCGM_FI_DEV_PAGE_RETIRED_PENDING'],
    gpuModels: [],
    driverBranches: [],
    updated: '2026-08-01',
    content:
      'DCGM fields expose retired pages, pending retirement, remapped rows, remap failure, and remaining remap capacity where supported. Preserve GPU UUID and sample time, and distinguish monotonic totals from current boolean health state.',
    documentedMeaning: 'The fields describe memory-page retirement and row-remapping state for supported GPUs.',
    nextEvidence: ['Collect remap failure, pending state, remaining capacity, and ECC counters for the same GPU UUID and time window.'],
    limitations: ['Field availability differs by GPU generation; one total without history does not show current growth.'],
  },
  {
    id: 'dcgm-clock-events',
    title: 'DCGM clock-event reasons for thermal and power limits',
    source: 'NVIDIA DCGM Field Identifiers',
    sourceUrl: 'https://docs.nvidia.com/datacenter/dcgm/latest/dcgm-api/dcgm-api-field-ids.html',
    authority: 'official',
    signalTypes: ['metric'],
    identifiers: ['DCGM_FI_DEV_CLOCKS_EVENT_REASONS', 'DCGM_FI_DEV_POWER_VIOLATION', 'DCGM_FI_DEV_THERMAL_VIOLATION'],
    gpuModels: [],
    driverBranches: [],
    updated: '2026-08-01',
    content:
      'DCGM clock-event and violation fields help distinguish thermal or power limiting from ordinary high temperature or board power. Correlate time-series deltas with clocks, utilization, workload phase, cooling, and configured limits.',
    documentedMeaning: 'The metrics report clock-event reasons and accumulated thermal or power violation time.',
    nextEvidence: ['Align clock-event reasons, SM clocks, power, temperature, and utilization on one benchmark timeline.'],
    limitations: ['A reason bit or accumulated counter does not by itself identify the platform-level root cause.'],
  },
  {
    id: 'dcgm-memory-usage',
    title: 'DCGM framebuffer memory usage and saturation',
    source: 'NVIDIA DCGM Field Identifiers',
    sourceUrl: 'https://docs.nvidia.com/datacenter/dcgm/latest/dcgm-api/dcgm-api-field-ids.html',
    authority: 'official',
    signalTypes: ['metric'],
    identifiers: ['DCGM_FI_DEV_FB_USED', 'DCGM_FI_DEV_FB_FREE'],
    gpuModels: [],
    driverBranches: [],
    updated: '2026-08-01',
    content:
      'DCGM framebuffer used and free fields report device-memory occupancy. A near-capacity snapshot can support a memory-pressure hypothesis, but allocator fragmentation and an out-of-memory failure require framework, process, and request-shape evidence.',
    documentedMeaning: 'The fields report used and free framebuffer memory on the GPU.',
    nextEvidence: ['Correlate memory use with process identity, model revision, batch or token shape, allocator statistics, and OOM logs.'],
    limitations: ['DCGM occupancy does not directly measure allocator fragmentation or prove that an OOM occurred.'],
  },
  {
    id: 'nvidia-nccl-troubleshooting',
    title: 'NCCL collective and network troubleshooting',
    source: 'NVIDIA NCCL User Guide',
    sourceUrl: 'https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/troubleshooting.html',
    authority: 'official',
    signalTypes: ['pipeline'],
    identifiers: ['NCCL_DEBUG', 'NCCL_DEBUG_SUBSYS', 'NCCL_ASYNC_ERROR_HANDLING'],
    gpuModels: [],
    driverBranches: [],
    updated: '2026-08-01',
    content:
      'NCCL troubleshooting separates interface selection, low-level fabric health, latency and bandwidth checks, and InfiniBand or RoCE diagnostics. Preserve rank, communicator, collective, timeout, topology, and NCCL debug output before changing transport settings.',
    documentedMeaning: 'NCCL provides diagnostics to localize collective failures across software, topology, and network layers.',
    nextEvidence: ['Capture NCCL INFO or WARN logs, rank and collective identity, topology, and point-to-point fabric tests for the same window.'],
    limitations: ['A collective timeout does not prove which rank, GPU, NIC, switch, or configuration caused the stall.'],
  },
  {
    id: 'nvidia-fabric-manager',
    title: 'Fabric Manager and NVSwitch runtime errors',
    source: 'NVIDIA Fabric Manager User Guide',
    sourceUrl: 'https://docs.nvidia.com/hgx-platforms/fabric-manager-user-guide/index.html',
    authority: 'official',
    signalTypes: ['pipeline', 'xid'],
    identifiers: ['SXID', 'NVSWITCH', 'FABRIC_MANAGER', 'CUDAERRORSYSTEMNOTREADY'],
    gpuModels: ['A100', 'H100', 'B100', 'GB200'],
    driverBranches: [],
    updated: '2025-12-01',
    content:
      'Fabric Manager initializes and manages NVSwitch fabrics on supported HGX and DGX systems. Runtime NVSwitch errors can be logged as SXid events on applicable platforms; platform behavior and recovery differ across A100, H100, and B200-class systems.',
    documentedMeaning: 'Fabric Manager and platform logs expose NVSwitch initialization, topology, and runtime-error state.',
    nextEvidence: ['Record platform generation, Fabric Manager service state, fabric registration, full SXid or NVSDM event, and affected topology.'],
    limitations: ['SXid handling and recovery are platform-specific; B200/B300 systems use different NVSwitch error telemetry.'],
  },
  {
    id: 'gpu-operator-mig',
    title: 'GPU Operator MIG configuration workflow',
    source: 'NVIDIA GPU Operator Documentation',
    sourceUrl: 'https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/gpu-operator-mig.html',
    authority: 'official',
    signalTypes: ['pipeline'],
    identifiers: ['NVIDIA.COM/MIG.CONFIG', 'MIG_MANAGER', 'MIG_STRATEGY'],
    gpuModels: ['A100', 'H100', 'H200'],
    driverBranches: [],
    updated: '2026-08-01',
    content:
      'GPU Operator uses MIG Manager and node labels to apply MIG geometry. Reconfiguration stops GPU clients and Operator pods and can require a node reboot, so nodes must be drained or cordoned according to change policy before profile changes.',
    documentedMeaning: 'MIG Manager reconciles the requested node MIG configuration and exposes success or failure through node labels.',
    nextEvidence: ['Inspect mig.config and mig.config.state labels, MIG Manager logs, active GPU workloads, and advertised allocatable resources.'],
    limitations: ['MIG profiles and reboot behavior vary by supported GPU and deployment environment.'],
  },
  {
    id: 'gpu-operator-device-plugin',
    title: 'Kubernetes GPU device allocation and scheduling',
    source: 'NVIDIA Kubernetes Device Plugin',
    sourceUrl: 'https://github.com/NVIDIA/k8s-device-plugin',
    authority: 'official',
    signalTypes: ['pipeline'],
    identifiers: ['NVIDIA.COM/GPU', 'NVIDIA_DEVICE_PLUGIN', 'ALLOCATABLE'],
    gpuModels: [],
    driverBranches: [],
    updated: '2026-08-01',
    content:
      'The NVIDIA device plugin advertises GPU resources to Kubernetes and participates in allocation. A Pending GPU workload requires inspection of requested resource names, node allocatable state, labels, taints, plugin pods, runtime configuration, and MIG strategy.',
    documentedMeaning: 'The device plugin makes NVIDIA GPU resources schedulable through Kubernetes extended resources.',
    nextEvidence: ['Compare pod requests with node allocatable resources, scheduling events, plugin logs, node labels, taints, and MIG strategy.'],
    limitations: ['A Pending pod is not necessarily a GPU hardware fault; scheduling, quota, affinity, and runtime configuration can block placement.'],
  },
  {
    id: 'gpu-operator-driver-init',
    title: 'GPU Operator driver and validator readiness',
    source: 'NVIDIA GPU Operator Troubleshooting',
    sourceUrl: 'https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/troubleshooting.html',
    authority: 'official',
    signalTypes: ['pipeline'],
    identifiers: ['NVIDIA_DRIVER_DAEMONSET', 'NVIDIA_OPERATOR_VALIDATOR', 'NVIDIA-SMI'],
    gpuModels: [],
    driverBranches: [],
    updated: '2026-08-01',
    content:
      'GPU Operator troubleshooting begins by checking ClusterPolicy status, operand pods, driver loading, container runtime configuration, and validator logs. Driver initialization failure should be separated from device-plugin, toolkit, and workload-level failures.',
    documentedMeaning: 'Operator and validator state identify which GPU software-stack component is not ready.',
    nextEvidence: ['Collect ClusterPolicy status, failing pod logs, node kernel messages, driver module state, nvidia-smi output, and runtime configuration.'],
    limitations: ['A failed validator indicates a stack-readiness problem but does not alone identify the underlying host or configuration cause.'],
  },
  {
    id: 'runbook-xid79',
    title: 'Runbook: preserve the PCIe failure timeline',
    source: 'GPU Signal Atlas Demonstration Runbook',
    sourceUrl: 'https://github.com/sivalinb/gpu-signal-atlas/blob/main/docs/RUNBOOKS.md',
    authority: 'internal',
    signalTypes: ['runbook', 'xid'],
    identifiers: ['XID 79', 'PCIE AER'],
    gpuModels: [],
    driverBranches: [],
    updated: '2026-08-29',
    content:
      'For an Xid 79 replay, freeze the time window, preserve earlier Xids and host AER records, check device enumeration, and compare PCIe replay-counter deltas. Escalate with the GPU UUID, bus address, node, driver, firmware, and workload. The demo never performs reset, drain, or reboot actions.',
    documentedMeaning: 'The local runbook defines the evidence package for a lost-GPU PCIe investigation.',
    nextEvidence: ['Create a timestamped evidence bundle before any disruptive recovery action.'],
    limitations: ['This demonstration runbook must be adapted to the organization’s hardware and change policy.'],
  },
  {
    id: 'runbook-ecc',
    title: 'Runbook: ECC evidence bundle',
    source: 'GPU Signal Atlas Demonstration Runbook',
    sourceUrl: 'https://github.com/sivalinb/gpu-signal-atlas/blob/main/docs/RUNBOOKS.md',
    authority: 'internal',
    signalTypes: ['runbook', 'xid', 'metric'],
    identifiers: ['XID 48', 'DCGM_FI_DEV_ECC_DBE_VOL_TOTAL'],
    gpuModels: [],
    driverBranches: [],
    updated: '2026-08-29',
    content:
      'For double-bit ECC signals, bind every counter to a GPU UUID and collection time. Compare volatile and aggregate counts, look for growth, preserve row-remapping or retirement state, and pair the metrics with Xid and recovery-action events.',
    documentedMeaning: 'The local runbook defines a time-bound ECC evidence package.',
    nextEvidence: ['Repeat the counter snapshot after a defined interval to distinguish history from new errors.'],
    limitations: ['This workflow gathers evidence; it does not authorize continued operation or hardware replacement.'],
  },
];

export const corpus: CorpusDocument[] = curatedDocuments.map((document) => ({
  ...document,
  provenance: provenance(document),
}));
