import type { CorpusDocument, SourceProvenance } from './types.ts';
import { curatedContentHash } from './ingestion.ts';

type CuratedDocument = Omit<CorpusDocument, 'provenance'>;

const REVIEW_DATE = '2026-08-29';

function provenance(document: CuratedDocument): SourceProvenance {
  const rolling = document.sourceUrl.includes('/latest/') || document.sourceUrl.includes('docs.fluentbit.io');
  return {
    sourceVersion: rolling ? `rolling documentation reviewed ${REVIEW_DATE}` : `source snapshot reviewed ${REVIEW_DATE}`,
    retrievedAt: REVIEW_DATE,
    sourceSection: document.title,
    curatedContentHash: curatedContentHash(document),
    reviewStatus: 'curated-demo-review',
  };
}

const curatedDocuments: CuratedDocument[] = [
  {
    id: 'nvidia-xid-79',
    title: 'Xid 79: GPU has fallen off the bus',
    source: 'NVIDIA Xid Errors',
    sourceUrl: 'https://docs.nvidia.com/deploy/xid-errors/analyzing-xid-catalog.html',
    authority: 'official',
    signalTypes: ['xid'],
    identifiers: ['XID 79', 'XID_79'],
    gpuModels: ['A100', 'H100', 'H200', 'B100', 'GB200'],
    driverBranches: [],
    updated: '2026-05-01',
    content:
      'Xid 79 is reported when the NVIDIA driver can no longer access a GPU over its PCI Express connection. The event text commonly says GPU has fallen off the bus. Investigation should include earlier Xid events, host PCIe Advanced Error Reporting messages, power delivery, physical connectivity, and whether the device remains visible to the operating system.',
    documentedMeaning:
      'The NVIDIA driver reports that the GPU is no longer accessible over its PCIe connection.',
    nextEvidence: [
      'Inspect earlier NVRM/Xid events for the same PCI bus address.',
      'Collect host PCIe AER messages and confirm whether the device is still enumerated.',
      'Record GPU model, driver branch, firmware, node, and workload identity.',
    ],
    limitations: [
      'Xid 79 alone does not distinguish GPU hardware, power, slot, riser, or host PCIe-path failures.',
      'Do not infer that a process restart can recover a device the host can no longer enumerate.',
    ],
  },
  {
    id: 'nvidia-xid-48',
    title: 'Xid 48: double-bit ECC error',
    source: 'NVIDIA Xid Errors',
    sourceUrl: 'https://docs.nvidia.com/deploy/xid-errors/analyzing-xid-catalog.html',
    authority: 'official',
    signalTypes: ['xid'],
    identifiers: ['XID 48', 'XID_48'],
    gpuModels: ['A100', 'H100', 'H200', 'B100', 'GB200'],
    driverBranches: [],
    updated: '2026-05-01',
    content:
      'Xid 48 is associated with an uncorrectable double-bit ECC memory error. Correlate the event with volatile and aggregate ECC counters, row-remapping or page-retirement status where supported, the affected GPU UUID, and any later recovery-action event.',
    documentedMeaning:
      'The GPU reported an uncorrectable double-bit ECC memory error.',
    nextEvidence: [
      'Collect volatile and aggregate double-bit ECC counters for the affected GPU.',
      'Inspect row-remapping or page-retirement status when the GPU supports it.',
      'Check for a subsequent recovery-action event and preserve the GPU UUID.',
    ],
    limitations: [
      'A single counter snapshot does not show whether errors are new, historical, or still increasing.',
    ],
  },
  {
    id: 'nvidia-xid-31',
    title: 'Xid 31: GPU memory page fault',
    source: 'NVIDIA Xid Errors',
    sourceUrl: 'https://docs.nvidia.com/deploy/xid-errors/analyzing-xid-catalog.html',
    authority: 'official',
    signalTypes: ['xid'],
    identifiers: ['XID 31', 'XID_31'],
    gpuModels: [],
    driverBranches: [],
    updated: '2026-05-01',
    content:
      'Xid 31 reports a GPU memory-management-unit page fault. Application address use, driver behavior, and hardware conditions may all require investigation. Preserve the process, channel, workload, and surrounding driver messages rather than treating the identifier as a complete root cause.',
    documentedMeaning: 'The GPU memory-management unit reported a page fault.',
    nextEvidence: [
      'Capture the affected process, workload, channel, and nearby driver messages.',
      'Reproduce with application memory-checking or debugging tools when safe.',
    ],
    limitations: ['The event does not by itself identify the faulty source-code location or prove hardware failure.'],
  },
  {
    id: 'nvidia-xid-13',
    title: 'Xid 13: graphics engine exception',
    source: 'NVIDIA Xid Errors',
    sourceUrl: 'https://docs.nvidia.com/deploy/xid-errors/analyzing-xid-catalog.html',
    authority: 'official',
    signalTypes: ['xid'],
    identifiers: ['XID 13', 'XID_13'],
    gpuModels: [],
    driverBranches: [],
    updated: '2026-05-01',
    content:
      'Xid 13 indicates a graphics-engine exception. The surrounding exception data, application behavior, driver branch, and reproducibility are needed to separate an application fault from driver or hardware conditions.',
    documentedMeaning: 'The GPU reported a graphics-engine exception.',
    nextEvidence: [
      'Preserve the complete Xid line and surrounding exception data.',
      'Record whether the event follows one workload or occurs across unrelated workloads.',
    ],
    limitations: ['The identifier is a symptom class, not a unique root cause.'],
  },
  {
    id: 'nvidia-xid-43',
    title: 'Xid 43: GPU stopped processing',
    source: 'NVIDIA Xid Errors',
    sourceUrl: 'https://docs.nvidia.com/deploy/xid-errors/analyzing-xid-catalog.html',
    authority: 'official',
    signalTypes: ['xid'],
    identifiers: ['XID 43', 'XID_43'],
    gpuModels: [],
    driverBranches: [],
    updated: '2026-05-01',
    content:
      'Xid 43 indicates a software-induced fault: an application hit a fault and the GPU stopped its work. NVIDIA describes the GPU as remaining healthy for this event class. Preserve the affected process and preceding events because Xid 43 does not identify the source-code location by itself.',
    documentedMeaning: 'An application fault stopped GPU work; the event class does not by itself indicate an unhealthy GPU.',
    nextEvidence: ['Identify the affected application or container and inspect its preceding CUDA and driver errors.'],
    limitations: ['Xid 43 does not identify the faulty instruction or justify labeling the GPU hardware unhealthy.'],
  },
  {
    id: 'nvidia-xid-154',
    title: 'Xid 154: GPU recovery action',
    source: 'NVIDIA Xid Errors',
    sourceUrl: 'https://docs.nvidia.com/deploy/xid-errors/working-with-xid-errors.html',
    authority: 'official',
    signalTypes: ['xid'],
    identifiers: ['XID 154', 'XID_154'],
    gpuModels: ['A100', 'H100', 'H200', 'B100', 'GB200'],
    driverBranches: ['R565', 'R570', 'R575', 'R580'],
    updated: '2026-05-01',
    content:
      'Newer drivers can emit Xid 154 to report a GPU recovery action associated with another Xid. Read it together with the initiating event and preserve the action reported by the driver instead of inventing a generic restart recommendation.',
    documentedMeaning: 'The driver reported a recovery-action classification associated with a GPU event.',
    nextEvidence: ['Find the initiating Xid and record the exact recovery action reported by the driver.'],
    limitations: ['Applicability and action vocabulary depend on GPU and driver support.'],
  },
  {
    id: 'dcgm-pcie-replay',
    title: 'DCGM PCIe replay counter',
    source: 'NVIDIA DCGM Field Identifiers',
    sourceUrl: 'https://docs.nvidia.com/datacenter/dcgm/latest/reference/dcgm-fields.html',
    authority: 'official',
    signalTypes: ['metric'],
    identifiers: ['DCGM_FI_DEV_PCIE_REPLAY_COUNTER'],
    gpuModels: [],
    driverBranches: [],
    updated: '2026-07-01',
    content:
      'DCGM_FI_DEV_PCIE_REPLAY_COUNTER represents PCIe replay activity. Treat it as a cumulative counter and compare its rate or delta over a known interval. A raw value without a baseline does not establish an active fault.',
    documentedMeaning: 'The metric records PCIe replay activity for the GPU connection.',
    nextEvidence: [
      'Calculate the counter increase over a defined time window.',
      'Correlate increases with PCIe AER logs, Xid events, and workload timing.',
    ],
    limitations: ['A cumulative absolute value without a baseline cannot show when the replays occurred.'],
  },
  {
    id: 'dcgm-gpu-temp',
    title: 'DCGM GPU temperature',
    source: 'NVIDIA DCGM Exporter Metrics',
    sourceUrl: 'https://docs.nvidia.com/datacenter/dcgm/latest/reference/dcgm-exporter-metrics.html',
    authority: 'official',
    signalTypes: ['metric'],
    identifiers: ['DCGM_FI_DEV_GPU_TEMP', 'DCGM_FI_DEV_GPU_TEMP_CELSIUS'],
    gpuModels: [],
    driverBranches: [],
    updated: '2026-07-01',
    content:
      'DCGM_FI_DEV_GPU_TEMP is exported as a gauge and represents GPU temperature in Celsius. Interpret it with thermal-violation and clock-event signals, workload utilization, fan or cooling state, and a time series rather than one point.',
    documentedMeaning: 'The gauge reports GPU temperature in degrees Celsius.',
    nextEvidence: ['Collect a temperature time series with GPU utilization, power, and thermal-violation metrics.'],
    limitations: ['A single temperature sample does not prove thermal throttling.'],
  },
  {
    id: 'dcgm-power-usage',
    title: 'DCGM board power usage',
    source: 'NVIDIA DCGM Exporter Metrics',
    sourceUrl: 'https://docs.nvidia.com/datacenter/dcgm/latest/reference/dcgm-exporter-metrics.html',
    authority: 'official',
    signalTypes: ['metric'],
    identifiers: ['DCGM_FI_DEV_POWER_USAGE', 'DCGM_FI_DEV_BOARD_POWER_WATTS'],
    gpuModels: [],
    driverBranches: [],
    updated: '2026-07-01',
    content:
      'The exported DCGM_FI_DEV_POWER_USAGE gauge maps to board power in watts. Compare it with configured power limits, clock-event reasons, utilization, and workload phase.',
    documentedMeaning: 'The gauge reports GPU board power usage in watts.',
    nextEvidence: ['Compare power, utilization, clock events, and the configured power limit over the same interval.'],
    limitations: ['High power use can be expected under load and is not itself a failure.'],
  },
  {
    id: 'dcgm-ecc-dbe',
    title: 'DCGM double-bit ECC counters',
    source: 'NVIDIA DCGM Exporter Metrics',
    sourceUrl: 'https://docs.nvidia.com/datacenter/dcgm/latest/reference/dcgm-exporter-metrics.html',
    authority: 'official',
    signalTypes: ['metric'],
    identifiers: ['DCGM_FI_DEV_ECC_DBE_VOL_TOTAL', 'DCGM_FI_DEV_ECC_DBE_AGG_TOTAL'],
    gpuModels: [],
    driverBranches: [],
    updated: '2026-07-01',
    content:
      'DCGM double-bit ECC metrics separate volatile and aggregate totals. Volatile values relate to the current driver lifecycle while aggregate values preserve a broader history. Use deltas, GPU identity, and related Xid events.',
    documentedMeaning: 'The metrics count uncorrectable double-bit ECC events over volatile or aggregate lifetimes.',
    nextEvidence: ['Compare volatile and aggregate counters and determine whether the volatile counter is increasing.'],
    limitations: ['Metric availability and exact behavior depend on the GPU and DCGM support.'],
  },
  {
    id: 'dcgm-exporter-selection',
    title: 'DCGM Exporter metric selection and availability',
    source: 'NVIDIA DCGM Exporter Documentation',
    sourceUrl: 'https://docs.nvidia.com/datacenter/dcgm/latest/reference/dcgm-exporter-metrics.html',
    authority: 'official',
    signalTypes: ['metric', 'pipeline'],
    identifiers: ['DCGM_EXP_XID_ERRORS_COUNT', 'DCGM_EXP_GPU_HEALTH_STATUS'],
    gpuModels: [],
    driverBranches: [],
    updated: '2026-07-01',
    content:
      'DCGM Exporter exposes selected fields in Prometheus format. Selecting a field does not guarantee runtime emission because support also depends on DCGM, hardware, entity type, permissions, and deployment configuration. Exporter-owned Xid count and health metrics can be enabled when supported.',
    documentedMeaning: 'DCGM Exporter publishes configured and supported GPU telemetry as Prometheus metrics.',
    nextEvidence: ['Verify the active collector configuration and inspect the exporter metrics endpoint.'],
    limitations: ['Configured fields may remain absent when unsupported by the runtime GPU or DCGM combination.'],
  },
  {
    id: 'gpu-operator-telemetry',
    title: 'GPU Operator and DCGM Exporter telemetry',
    source: 'NVIDIA GPU Operator Documentation',
    sourceUrl: 'https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/getting-started.html',
    authority: 'official',
    signalTypes: ['pipeline', 'metric'],
    identifiers: ['GPU_OPERATOR', 'DCGM_EXPORTER'],
    gpuModels: [],
    driverBranches: [],
    updated: '2026-07-01',
    content:
      'The NVIDIA GPU Operator can deploy and manage DCGM and DCGM Exporter in Kubernetes. Exporter metrics can be associated with Kubernetes workloads through the pod-resources integration and scraped by Prometheus.',
    documentedMeaning: 'GPU Operator can supply the Kubernetes components used to expose DCGM telemetry.',
    nextEvidence: ['Verify exporter pods, ServiceMonitor discovery, and workload labels before debugging missing series.'],
    limitations: ['Installing the Operator does not guarantee that every optional field is enabled or supported.'],
  },
  {
    id: 'fluent-bit-kubernetes',
    title: 'Fluent Bit Kubernetes metadata enrichment',
    source: 'Fluent Bit Official Manual',
    sourceUrl: 'https://docs.fluentbit.io/manual/pipeline/filters/kubernetes',
    authority: 'official',
    signalTypes: ['pipeline'],
    identifiers: ['KUBERNETES_FILTER', 'FLUENT_BIT'],
    gpuModels: [],
    driverBranches: [],
    updated: '2026-03-01',
    content:
      'The Fluent Bit Kubernetes filter can enrich tailed container records with pod, namespace, container, owner, label, and annotation metadata. Correct tags, file paths, parser registration, and API or Kubelet access are prerequisites.',
    documentedMeaning: 'The Kubernetes filter attaches workload metadata to container log records.',
    nextEvidence: ['Verify the input tag, tag prefix, parser, service-account access, and metadata cache behavior.'],
    limitations: ['Host kernel logs need an explicit mapping strategy because they are not inherently pod-scoped.'],
  },
  {
    id: 'fluent-bit-otlp',
    title: 'Fluent Bit OpenTelemetry output',
    source: 'Fluent Bit Official Manual',
    sourceUrl: 'https://docs.fluentbit.io/manual/data-pipeline/outputs/opentelemetry',
    authority: 'official',
    signalTypes: ['pipeline'],
    identifiers: ['OTLP', 'FLUENT_BIT', '/V1/LOGS'],
    gpuModels: [],
    driverBranches: [],
    updated: '2026-05-01',
    content:
      'The Fluent Bit OpenTelemetry output can send logs, metrics, and traces to OpenTelemetry endpoints. Configure the destination, signal URI, transport, retry policy, TLS, and record-to-OTel field mappings deliberately.',
    documentedMeaning: 'Fluent Bit can forward supported telemetry signals to an OpenTelemetry endpoint.',
    nextEvidence: ['Confirm endpoint reachability, /v1/logs response status, retry behavior, TLS, and field mappings.'],
    limitations: ['Successful forwarding does not guarantee that downstream storage indexed every attribute.'],
  },
  {
    id: 'otel-semconv',
    title: 'OpenTelemetry semantic conventions',
    source: 'OpenTelemetry Specification',
    sourceUrl: 'https://opentelemetry.io/docs/specs/semconv/',
    authority: 'official',
    signalTypes: ['pipeline'],
    identifiers: ['OTEL', 'SEMANTIC_CONVENTIONS', 'TRACE_ID', 'SPAN_ID'],
    gpuModels: [],
    driverBranches: [],
    updated: '2026-08-01',
    content:
      'OpenTelemetry semantic conventions define common names and meanings for resource attributes, logs, metrics, spans, and events. Preserve original vendor identifiers such as Xid and DCGM field names while adding stable resource context such as service, host, and Kubernetes identity.',
    documentedMeaning: 'Semantic conventions provide consistent attribute naming across telemetry producers and consumers.',
    nextEvidence: ['Record the convention version and validate required resource identifiers at the collector boundary.'],
    limitations: ['Not every GPU-specific attribute has a stable cross-vendor semantic convention.'],
  },
  {
    id: 'runbook-xid79',
    title: 'Runbook: preserve the PCIe failure timeline',
    source: 'GPU Signal Atlas Demonstration Runbook',
    sourceUrl: 'https://github.com/sivalinb/gpu-signal-atlas/blob/main/docs/RUNBOOKS.md',
    authority: 'internal',
    signalTypes: ['runbook', 'xid'],
    identifiers: ['XID 79', 'PCIE AER'],
    gpuModels: [],
    driverBranches: [],
    updated: '2026-08-29',
    content:
      'For an Xid 79 replay, freeze the time window, preserve earlier Xids and host AER records, check device enumeration, and compare PCIe replay-counter deltas. Escalate with the GPU UUID, bus address, node, driver, firmware, and workload. The demo never performs reset, drain, or reboot actions.',
    documentedMeaning: 'The local runbook defines the evidence package for a lost-GPU PCIe investigation.',
    nextEvidence: ['Create a timestamped evidence bundle before any disruptive recovery action.'],
    limitations: ['This demonstration runbook must be adapted to the organization’s hardware and change policy.'],
  },
  {
    id: 'runbook-ecc',
    title: 'Runbook: ECC evidence bundle',
    source: 'GPU Signal Atlas Demonstration Runbook',
    sourceUrl: 'https://github.com/sivalinb/gpu-signal-atlas/blob/main/docs/RUNBOOKS.md',
    authority: 'internal',
    signalTypes: ['runbook', 'xid', 'metric'],
    identifiers: ['XID 48', 'DCGM_FI_DEV_ECC_DBE_VOL_TOTAL'],
    gpuModels: [],
    driverBranches: [],
    updated: '2026-08-29',
    content:
      'For double-bit ECC signals, bind every counter to a GPU UUID and collection time. Compare volatile and aggregate counts, look for growth, preserve row-remapping or retirement state, and pair the metrics with Xid and recovery-action events.',
    documentedMeaning: 'The local runbook defines a time-bound ECC evidence package.',
    nextEvidence: ['Repeat the counter snapshot after a defined interval to distinguish history from new errors.'],
    limitations: ['This workflow gathers evidence; it does not authorize continued operation or hardware replacement.'],
  },
];

export const corpus: CorpusDocument[] = curatedDocuments.map((document) => ({
  ...document,
  provenance: provenance(document),
}));
