import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

import { corpus } from '../core/corpus.ts';
import { corpusVectorHash, documentText, embed, EMBEDDING_DIMENSIONS } from '../core/vector.ts';

const output = fileURLToPath(new URL('../core/generated/vector-index.ts', import.meta.url));
const vectors = Object.fromEntries(
  corpus.map((document) => [
    document.id,
    embed(documentText(document)).map((value) => Number(value.toFixed(12))),
  ]),
);

const body = `// Generated by \`npm run index:build\`. Do not edit by hand.\nexport const precomputedVectorIndex = ${JSON.stringify(
  {
    version: '2026-09-02-index-2',
    dimensions: EMBEDDING_DIMENSIONS,
    corpusHash: corpusVectorHash(corpus),
    generatedAt: '2026-09-02',
    vectors,
  },
  null,
  2,
)} as const;\n`;

await writeFile(output, body, 'utf8');
console.log(`Wrote ${corpus.length} vectors (${EMBEDDING_DIMENSIONS} dimensions) to ${output}`);
